const data = [
  {
    id: 1,
    name: 'First note',
    creationDate: '01/01/2022',
    category: 'Idea',
    content: 'some content',
    dates: 'just date',
    archive: false,
  },
  {
    id: 2,
    name: 'First note',
    creationDate: '01/01/2022',
    category: 'Idea',
    content: 'some content',
    dates: 'just date',
    archive: false,
  },
  {
    id: 3,
    name: 'First note',
    creationDate: '01/01/2022',
    category: 'Task',
    content: 'some content',
    dates: 'just date',
    archive: false,
  },
  {
    id: 4,
    name: 'First note',
    creationDate: '01/01/2022',
    category: 'Task',
    content: 'some content',
    dates: 'just date',
    archive: false,
  },
  {
    id: 5,
    name: 'Second note',
    creationDate: '01/01/2023',
    category: 'Random Thought',
    content: 'some content',
    dates: 'just date',
    archive: false,
  },
  {
    id: 6,
    name: 'Fith note',
    creationDate: '01/01/2023',
    category: 'Random Thought',
    content: 'some content',
    dates: 'just date',
    archive: false,
  },
  {
    id: 7,
    name: 'Third note',
    creationDate: '01/01/2023',
    category: 'Idea',
    content: 'some content',
    dates: 'just date 02/02/2022',
    archive: false,
  },
  {
    id: 8,
    name: 'Second note',
    creationDate: '01/01/2032',
    category: 'Idea',
    content: 'some content',
    dates: 'just date',
    archive: true,
  },
  {
    id: 9,
    name: 'Second note',
    creationDate: '01/01/2032',
    category: 'Idea',
    content: 'some content',
    dates: 'just date',
    archive: true,
  },
  {
    id: 10,
    name: 'Second note',
    creationDate: '01/01/2032',
    category: 'Idea',
    content: 'some content',
    dates: 'just date',
    archive: true,
  },
  {
    id: 11,
    name: 'Second note',
    creationDate: '01/01/2032',
    category: 'Idea',
    content: 'some content',
    dates: 'just date',
    archive: true,
  },
  {
    id: 12,
    name: 'Second note',
    creationDate: '01/01/2032',
    category: 'Idea',
    content: 'some content',
    dates: 'just date',
    archive: true,
  },
];

export { data };
